import  Card  from "@/components/Card";
import Image from "next/image";

export default function Home() {
  return (
    <div>
<Card 
sgender="Female"
sname="Anudari"
semail="anudariochiredene@gmail.com"
studentcode="26bs801324"
/>
<Card 
sgender="Female"
sname="Anudari"
semail="anudariochiredene@gmail.com"
studentcode="26bs801324"
/>
<Card 
sgender="Female"
sname="Anudari"
semail="anudariochiredene@gmail.com"
studentcode="26bs801324"
/>
</div>  );
}
<Card
        sgender="Male"
        sname="Baasandorj.E"
        semail="baskaerka763@gmail.com"
        studentcode="25BS65476"
      />
      <Card
        sgender="Male"
        sname="Nyambayar.T"
        semail="yunoxsama00@gmail.com"
        studentcode="25LP7381"
      />
      <Card
        sgender="Female"
        sname="Dolgoonzul.L"
        semail="dolgoonlkhagva@gmail.com"
        studentcode="26BS86071"
      />
      <Card
        sgender="Female"
        sname="Nomin.G"
        semail="gnomin200408@gmail.com"
        studentcode="25BS52373"
      />
      <Card
        sgender="Male"
        sname="Nyamochir.L"
        semail="yunoxsama00@gmail.com"
        studentcode="26BS98744"
      />
      <Card
        sgender="Male"
        sname="Aznorov.M"
        semail="azaamunkhtn@gmail.com"
        studentcode="25LP1286"
      />
      <Card
        sgender="Male"
        sname="Bilegsaikhan.B"
        semail="bbek3201@gmail.com"
        studentcode="26BS83263"
      />
      <Card
        sgender="Male"
        sname="Batmagnai.Sh"
        semail="sbatmagnai25@gmail.com"
        studentcode="25LP6073"
      />
      <Card
        sgender="Male"
        sname="Chinzorig.B"
        semail="chinzoobatbold11@gmail.com"
        studentcode="26BS13491"
      />
      <Card
        sgender="Male"
        sname="Gaajadamba.B"
        semail="gaajadamba@gmail.com"
        studentcode="26BS25985"
      />
      <Card
        sgender="Male"
        sname="Monkh-Orgil.B"
        semail="suusiibat@gmail.com"
        studentcode="26BS98744"
      />
      <Card
        sgender="Male"
        sname="Batkhuleg.T"
        semail="t.khuleg@gmail.com"
        studentcode="26BS38301"
      />
      <Card
        sgender="Male"
        sname="Ornuun.K"
        semail="urnuun919@gmail.com"
        studentcode="25BS21438"
      />
      <Card
        sgender="Male"
        sname="Tsolmon.B"
        semail="btsolmon.mn@gmail.com"
        studentcode="26BS11043"
      />
      <Card
        sgender="Male"
        sname="Bilguuntogs.A"
        semail="bilgntgsamarbayr@gmail.com"
        studentcode="26BS10652"
      />
      <Card
        sgender="Female"
        sname="Nominerdene.Ts"
        semail="nominerdenetsogtbaatar5@gmail.com"
        studentcode="26BS60931"
      />
      <Card
        sgender="Female"
        sname="Nominerdene.E"
        semail="ne78693@gmail.com"
        studentcode="26BS42529"
      />
      <Card
        sgender="Male"
        sname="Bayarbileg.A"
        semail="bayarbileg.am@gmail.com"
        studentcode="26BS44296"
      />
      <Card
        sgender="Male"
        sname="Telmuun.M"
        semail="bilgntgsamarbayr@gmail.com"
        studentcode="26BS10652"
      />
      <Card
        sgender="Male"
        sname="Bilguuntogs.A"
        semail="bilgntgsamarbayr@gmail.com"
        studentcode="26BS10652"
      />
      <Card
        sgender="Male"
        sname="Bilguuntogs.A"
        semail="bilgntgsamarbayr@gmail.com"
        studentcode="26BS10652"
      />
    </div>
  );
}
